### ISSUE TITLE
kazıma yapmıyor...

### ISSUE THREAD

**Issue by rfve** [ediziks/scrapy-with-docker#1]
Hello

docker-compose up --build
I ran it in the form of
in another terminal
docker exec -it mysql bash
That's how I worked it, but.
The products appear empty in the database. I've also changed the products, but it doesn't scrape.

is another python command required to work

**Comment by ediziks** [comment]
hi @rfve, it's not an updated script and it won't be anytime soon. also, it's been a while since I last checked It but the issue may be related to HTML paths of hepsiburada that we need to provide in scrapy. Closing the issue since the repo is inactive, better to use it as a template so it will give an idea about its working logic.
